### ISSUE TITLE
Help: need clarification on boxing

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#7]
For the struct and map type, in what order do I need to unbox the types? i.e. BFS or DFS? Is the following correct?

For maps, i unbox the key and value type before unboxing any of the values:
```
unbox(mapType.getKeyType())
unbox(mapType.getValueType())
for each entry {
  unbox(entry.key)
  unbox(entry.value)
}
```
For structs, I unbox the field types as I encounter the field values:
```
for each field {
  unbox(structType.getField(idx).getType())
  unbox(struct.getField(idx))
}
```

**Comment by pmuetschard** [comment]
Another question: do parameters of a service.Command share their context (for back references) or does each parameter start a new context?

**Comment by ben-clayton** [comment]
Instead of trying to describe the algorithm (where I'll most likely get it wrong), take a look at this code for [boxing](https://github.com/ben-clayton/gapid/blob/protos/gapis/service/box/box.go#L103-L127), and [unboxing](https://github.com/ben-clayton/gapid/blob/protos/gapis/service/box/box.go#L217-L235).

Note that types are also back-referenced when referenced from `Value`s.

> Another question: do parameters of a service.Command share their context (for back references) or does each parameter start a new context?

The back-refs are not brought across when crossing the boundary from `box.proto` into another proto. As such, parameters do not share back references.
